### ISSUE TITLE
does edenjs need to be installed locally or only globally?

### ISSUE THREAD

**Issue by kzap** [Sterling-Technologies/evejs#50]
followed readme and got this:

andremarcelo-tanner$ eve
[eve] watching on server, admin, web
[eve] Server has started ...

module.js:340
    throw err;
          ^
Error: Cannot find module 'edenjs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/andremarcelo-tanner/Documents/Web Page/NameSpace Eve/deploy/server/controller.js:1:74)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

andremarcelo-tanner$ npm -g list
/usr/local/lib
├─┬ eve-pms@0.0.10
│ ├─┬ chokidar@0.10.5
│ │ ├── async-each@0.1.6
│ │ ├─┬ fsevents@0.3.1
│ │ │ └── nan@1.3.0
│ │ └─┬ readdirp@1.1.0
│ │   ├── graceful-fs@2.0.3
│ │   ├─┬ minimatch@0.2.14
│ │   │ ├── lru-cache@2.5.0
│ │   │ └── sigmund@1.0.0
│ │   └─┬ readable-stream@1.0.33
│ │     ├── core-util-is@1.0.1
│ │     ├── inherits@2.0.1
│ │     ├── isarray@0.0.1
│ │     └── string_decoder@0.10.31
│ ├─┬ edenjs@0.0.28

**Comment by cjzamora** [comment]
need to:

`$cd deploy/server` 
then 
`$npm install`
 or
`npm install deploy/server`

**Comment by kzap** [comment]
pa added sa readme

**Comment by kzap** [comment]
npm install deploy/server doesnt work or installs into the wrong dir
have to cd to deploy/server

**Comment by cjzamora** [comment]
Oh yeah need to `cd` on `deploy/server` :) need to add it on README.
